version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_URL=http://localhost:3001/api/v1
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"